from django import template

register = template.Library()


CATEGORY_TRANSLATIONS = {
    'Beef': 'Carne',
    'Chicken': 'Frango',
    'Dessert': 'Sobremesa',
    'Lamb': 'Cordeiro',
    'Miscellaneous': 'Diversos',
    'Pasta': 'Massa',
    'Pork': 'Porco',
    'Seafood': 'Frutos do mar',
    'Side': 'Acompanhamento',
    'Starter': 'Entrada',
    'Vegan': 'Vegano',
    'Vegetarian': 'Vegetariano',
    'Breakfast': 'Café da manhã',
    'Goat': 'Cabrito',
}


@register.filter
def traduzir_categoria(nome):
    """Traduz nome de categoria da TheMealDB pra pt-BR.
    Se a categoria não estiver no dicionário, retorna o nome original."""
    if not nome:
        return nome
    return CATEGORY_TRANSLATIONS.get(nome, nome)


AREA_TRANSLATIONS = {
    'Afghan': 'Afegã',
    'Albanian': 'Albanesa',
    'Algerian': 'Argelina',
    'American': 'Americana',
    'Andorran': 'Andorrana',
    'Angolan': 'Angolana',
    'Antiguan, Barbudan': 'Antiguana e Barbudense',
    'Argentine': 'Argentina',
    'Armenian': 'Armênia',
    'Aruban': 'Arubana',
    'Australian': 'Australiana',
    'Austrian': 'Austríaca',
    'Azerbaijani': 'Azerbaijana',
    'Bahamian': 'Bahamense',
    'Bahraini': 'Barenita',
    'Bangladeshi': 'Bengali',
    'Barbadian': 'Barbadiana',
    'Belarusian': 'Bielorrussa',
    'Belgian': 'Belga',
    'Belizean': 'Belizenha',
    'Beninese': 'Beninense',
    'Bermudian': 'Bermudense',
    'Bhutanese': 'Butanesa',
    'Bolivian': 'Boliviana',
    'Bosnian, Herzegovinian': 'Bósnia e Herzegovina',
    'Brazilian': 'Brasileira',
    'British': 'Britânica',
    'Bruneian': 'Bruneana',
    'Bulgarian': 'Búlgara',
    'Burkinabe': 'Burquinense',
    'Burmese': 'Birmanesa',
    'Burundian': 'Burundiana',
    'Cambodian': 'Cambojana',
    'Cameroonian': 'Camaronesa',
    'Canadian': 'Canadense',
    'Cape Verdian': 'Cabo-verdiana',
    'Caymanian': 'Caimanense',
    'Central African': 'Centro-Africana',
    'Chadian': 'Chadiana',
    'Channel Islander': 'Anglo-normanda',
    'Chilean': 'Chilena',
    'Chinese': 'Chinesa',
    'Colombian': 'Colombiana',
    'Congolese': 'Congolesa',
    'Costa Rican': 'Costa-riquenha',
    'Croatian': 'Croata',
    'Cuban': 'Cubana',
    'Cypriot': 'Cipriota',
    'Czech': 'Tcheca',
    'Danish': 'Dinamarquesa',
    'Djibouti': 'Djibutiana',
    'Dominican': 'Dominicana',
    'Dutch': 'Holandesa',
    'Ecuadorean': 'Equatoriana',
    'Egyptian': 'Egípcia',
    'Emirati': 'Emiradense',
    'Equatorial Guinean': 'Equato-guineense',
    'Eritrean': 'Eritreia',
    'Estonian': 'Estoniana',
    'Ethiopian': 'Etíope',
    'Faroese': 'Feroense',
    'Fijian': 'Fijiana',
    'Filipino': 'Filipina',
    'Finnish': 'Finlandesa',
    'French': 'Francesa',
    'Gabonese': 'Gabonesa',
    'Gambian': 'Gambiana',
    'Georgian': 'Georgiana',
    'German': 'Alemã',
    'Ghanaian': 'Ganesa',
    'Gibraltar': 'Gibraltariana',
    'Greek': 'Grega',
    'Greenlandic': 'Groenlandesa',
    'Grenadian': 'Granadina',
    'Guadeloupian': 'Guadalupense',
    'Guamanian': 'Guamana',
    'Guatemalan': 'Guatemalteca',
    'Guinea-Bissauan': 'Guineense (Bissau)',
    'Guinean': 'Guineense',
    'Guyanese': 'Guianense',
    'Haitian': 'Haitiana',
    'Honduran': 'Hondurenha',
    'Hong Konger': 'Hongconguesa',
    'Hungarian': 'Húngara',
    'Icelander': 'Islandesa',
    'Indian': 'Indiana',
    'Indonesian': 'Indonésia',
    'Iranian': 'Iraniana',
    'Iraqi': 'Iraquiana',
    'Irish': 'Irlandesa',
    'Israeli': 'Israelense',
    'Italian': 'Italiana',
    'Ivorian': 'Marfinense',
    'Jamaican': 'Jamaicana',
    'Japanese': 'Japonesa',
    'Jordanian': 'Jordaniana',
    'Kazakhstani': 'Cazaque',
    'Kenyan': 'Queniana',
    'Kirghiz': 'Quirguiz',
    'Kosovar': 'Kosovar',
    'Kuwaiti': 'Kuwaitiana',
    'Laotian': 'Laosiana',
    'Latvian': 'Letã',
    'Lebanese': 'Libanesa',
    'Liberian': 'Liberiana',
    'Libyan': 'Líbia',
    'Liechtensteiner': 'Liechtensteinense',
    'Lithuanian': 'Lituana',
    'Luxembourger': 'Luxemburguesa',
    'Macedonian': 'Macedônia',
    'Malagasy': 'Malgaxe',
    'Malawian': 'Malauiana',
    'Malaysian': 'Malaia',
    'Maldivan': 'Maldiva',
    'Malian': 'Maliana',
    'Maltese': 'Maltesa',
    'Mauritian': 'Mauriciana',
    'Mexican': 'Mexicana',
    'Moldovan': 'Moldava',
    'Mongolian': 'Mongol',
    'Montenegrin': 'Montenegrina',
    'Moroccan': 'Marroquina',
    'Mosotho': 'Lesotense',
    'Motswana': 'Botsuana',
    'Mozambican': 'Moçambicana',
    'Namibian': 'Namibiana',
    'Nepalese': 'Nepalesa',
    'New Zealander': 'Neozelandesa',
    'Ni-Vanuatu': 'Vanuatuense',
    'Nicaraguan': 'Nicaraguense',
    'Nigerian': 'Nigeriana',
    'Nigerien': 'Nigerina',
    'North Korean': 'Norte-Coreana',
    'Norwegian': 'Norueguesa',
    'Omani': 'Omanense',
    'Pakistani': 'Paquistanesa',
    'Palestinian': 'Palestina',
    'Panamanian': 'Panamenha',
    'Papua New Guinean': 'Papua-Guineense',
    'Paraguayan': 'Paraguaia',
    'Peruvian': 'Peruana',
    'Polish': 'Polonesa',
    'Portuguese': 'Portuguesa',
    'Puerto Rican': 'Porto-riquenha',
    'Qatari': 'Catariana',
    'Romanian': 'Romena',
    'Russian': 'Russa',
    'Rwandan': 'Ruandesa',
    'Saint Lucian': 'Santa-lucense',
    'Salvadoran': 'Salvadorenha',
    'Sammarinese': 'San-marinense',
    'Samoan': 'Samoana',
    'Saudi Arabian': 'Saudita',
    'Senegalese': 'Senegalesa',
    'Serbian': 'Sérvia',
    'Seychellois': 'Seichelense',
    'Sierra Leonean': 'Serra-leonense',
    'Singaporean': 'Singapurense',
    'Slovak': 'Eslovaca',
    'Slovene': 'Eslovena',
    'Solomon Islander': 'Salomônica',
    'Somali': 'Somali',
    'South African': 'Sul-Africana',
    'South Korean': 'Sul-Coreana',
    'South Sudanese': 'Sul-Sudanesa',
    'Spanish': 'Espanhola',
    'Sri Lankan': 'Cingalesa',
    'Sudanese': 'Sudanesa',
    'Surinamer': 'Surinamesa',
    'Swedish': 'Sueca',
    'Swiss': 'Suíça',
    'Syrian': 'Síria',
    'Tadzhik': 'Tadjique',
    'Taiwanese': 'Taiwanesa',
    'Tanzanian': 'Tanzaniana',
    'Thai': 'Tailandesa',
    'Togolese': 'Togolesa',
    'Tongan': 'Tonganesa',
    'Trinidadian': 'Trinitária',
    'Tunisian': 'Tunisiana',
    'Turkish': 'Turca',
    'Turkmen': 'Turcomana',
    'Tuvaluan': 'Tuvaluana',
    'Ugandan': 'Ugandense',
    'Ukrainian': 'Ucraniana',
    'Uruguayan': 'Uruguaia',
    'Uzbekistani': 'Uzbeque',
    'Venezuelan': 'Venezuelana',
    'Vietnamese': 'Vietnamita',
    'Yemeni': 'Iemenita',
    'Zambian': 'Zambiana',
    'Zimbabwean': 'Zimbabuana',
}


@register.filter
def traduzir_cozinha(nome):
    """Traduz nome de cozinha (area) da TheMealDB pra pt-BR.
    Se a cozinha não estiver no dicionário, retorna o nome original."""
    if not nome:
        return nome
    return AREA_TRANSLATIONS.get(nome, nome)
